/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import appcode.Session;
import appcode.form.RoundedGradientButton;
import appcode.table.TableActionCellEditor;
import appcode.table.TableActionCellRender;
import appcode.table.TableActionEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Koneksi;

/**
 *
 * @author coyha
 */
public class MenuPenyewaan extends javax.swing.JPanel {

    /**
     * Creates new form MenuHome
     */
    DefaultTableModel model;
    Connection conn = new Koneksi().connect();
    public MenuPenyewaan() {
        initComponents();

        String roleNya = Session.getRole();
        if (roleNya.equalsIgnoreCase("guest")) {
            jTabbedPane1.remove(0);
            loadDataPenyewaan();
            tblDataPenyewaan.fixTable(jScrollPane1);
        } else if (roleNya.equalsIgnoreCase("admin")) {
            loadDataAmbulan();
            tblDataAmbulan.fixTable(jScrollPane2);
        }
        
        jTabbedPane1.addChangeListener((ChangeEvent e) -> {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            if (selectedIndex == 0) {
                loadDataAmbulan();
                tblDataAmbulan.fixTable(jScrollPane2);
            } else if (selectedIndex == 1) {
                loadDataPenyewaan();
                tblDataPenyewaan.fixTable(jScrollPane1);     
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataAmbulan = new appcode.table.TableDark();
        btnAddAmbulan = new RoundedGradientButton("Tambah");
        btnReport1 = new RoundedGradientButton("Report");
        txtSearch = new appcode.form.CustomTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataPenyewaan = new appcode.table.TableDark();
        btnAddPenyewaan = new RoundedGradientButton("Tambah");
        btnReport = new RoundedGradientButton("Report");
        txtSearchPenyewaan = new appcode.form.CustomTextField();

        setBackground(new java.awt.Color(45, 48, 51));
        setPreferredSize(new java.awt.Dimension(1105, 793));

        jTabbedPane1.setForeground(new java.awt.Color(204, 102, 0));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(932, 745));

        jPanel2.setBackground(new java.awt.Color(45, 48, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ambulan");

        tblDataAmbulan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDataAmbulan);

        btnAddAmbulan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddAmbulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAmbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAmbulanActionPerformed(evt);
            }
        });

        btnReport1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(138, 138, 138));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setPlaceholder("Cari");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(672, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Ambulan", jPanel2);

        jPanel1.setBackground(new java.awt.Color(45, 48, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Penyewaan");

        tblDataPenyewaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataPenyewaan);

        btnAddPenyewaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddPenyewaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPenyewaanActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        txtSearchPenyewaan.setBackground(new java.awt.Color(138, 138, 138));
        txtSearchPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchPenyewaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchPenyewaan.setPlaceholder("Cari");
        txtSearchPenyewaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchPenyewaanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 438, Short.MAX_VALUE)
                        .addComponent(txtSearchPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearchPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penyewaan Ambulan", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPenyewaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPenyewaanActionPerformed
        // TODO add your handling code here:
        setupDialogPenyewaan().setVisible(true);
    }//GEN-LAST:event_btnAddPenyewaanActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnAddAmbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAmbulanActionPerformed
        // TODO add your handling code here:
        setupDialogAmbulan().setVisible(true);
    }//GEN-LAST:event_btnAddAmbulanActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        loadDataAmbulan();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchPenyewaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPenyewaanKeyReleased
        // TODO add your handling code here:
        loadDataPenyewaan();
    }//GEN-LAST:event_txtSearchPenyewaanKeyReleased

    private void loadDataAmbulan(){
        String sql = "SELECT id, nomor_polisi, sopir, kapasitas, status, keterangan FROM ambulan WHERE 1 = 1";

        String search = txtSearch.getText();
        if (!search.isEmpty()) {
            sql += " AND ( " +
                   "nomor_polisi LIKE '%" + search + "%' OR " +
                   "sopir LIKE '%" + search + "%' OR " +
                   "status LIKE '%" + search + "%' OR " +
                   "keterangan LIKE '%" + search + "%' " +
                   ")";
        }

        sql += " ORDER BY id DESC";

        Object[] Baris = {
            "No",
            "Action",
            "Plat No",
            "Sopir",
            "Kapasitas",
            "Status",
            "Keterangan"
        };

        
        model = new DefaultTableModel(null, Baris);
        tblDataAmbulan.setModel(model);
        
        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int num = 1;
            while(hasil.next()){
                String[] data={
                    Integer.toString(num), 
                    hasil.getString("id"), 
                    hasil.getString("nomor_polisi"), 
                    hasil.getString("sopir"), 
                    hasil.getString("kapasitas"), 
                    hasil.getString("status"),
                    hasil.getString("keterangan")
                };
                model.addRow(data);
                num++;
            }
            TableActionEvent actionEvent = new TableActionEvent() {
                @Override
                public void onEdit(int row) {
                    DialogAmbulanAddEdit dialog = setupDialogAmbulan();
                    System.out.print(model.getValueAt(row, 1).toString());
                    dialog.setData(Integer.parseInt(model.getValueAt(row, 1).toString()));
                    dialog.setVisible(true);
                }

                @Override
                public void onDelete(int row) {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "Konfirmasi hapus ambulan?","Warning",dialogButton);
                    if(dialogResult == JOptionPane.YES_OPTION){
                        String kode = model.getValueAt(row, 1).toString();
                        try{
                            String sqlDeletePenyewaan = "DELETE FROM penyewaan_ambulan WHERE ambulan_id = ?";
                            PreparedStatement statPenyewaan = conn.prepareStatement(sqlDeletePenyewaan);
                            statPenyewaan.setString(1, kode);
                            statPenyewaan.executeUpdate();

                            String sqlDeleteAmbulan = "DELETE FROM ambulan WHERE id = ?";
                            PreparedStatement statAmbulan = conn.prepareStatement(sqlDeleteAmbulan);
                            statAmbulan.setString(1, kode);
                            statAmbulan.executeUpdate();
                            
                            JOptionPane.showMessageDialog(null, "Ambulan Berhasil Dihapus");
                            loadDataAmbulan();
                        }catch (SQLException e){
                            JOptionPane.showMessageDialog(null, "Ambulan Gagal Dihapus "+e);
                        }
                    }
                }
            };
            tblDataAmbulan.getColumnModel().getColumn(1).setCellRenderer(new TableActionCellRender());
            tblDataAmbulan.getColumnModel().getColumn(1).setCellEditor(new TableActionCellEditor(actionEvent));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private DialogAmbulanAddEdit setupDialogAmbulan() {
        DialogAmbulanAddEdit dialog = new DialogAmbulanAddEdit(null, true);
        dialog.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                
            }

            @Override
            public void windowClosing(WindowEvent e) {
                
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadDataAmbulan();
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                
            }
        });
        return dialog;
    }
    
    private void loadDataPenyewaan(){
        String sql = "SELECT p.*, " +
                    "a.nomor_polisi, " +
                    "a.sopir " +
                    "FROM penyewaan_ambulan p " +
                    "INNER JOIN ambulan a ON p.ambulan_id = a.id " +
                    "WHERE 1 = 1";

       String search = txtSearch.getText();
       if (!search.isEmpty()) {
           sql += " AND (" +
                  "a.nomor_polisi LIKE '%" + search + "%' OR " +
                  "a.sopir LIKE '%" + search + "%' OR " +
                  "p.lokasi_jemput LIKE '%" + search + "%' OR " +
                  "p.lokasi_tujuan LIKE '%" + search + "%' OR " +
                  "p.waktu_jemput LIKE '%" + search + "%' OR " +
                  "p.status LIKE '%" + search + "%' OR " +
                  "p.keterangan LIKE '%" + search + "%'" +
                  ")";
       }

       sql += " ORDER BY p.id DESC";

       Object[] Baris = {
           "No",
           "Action",
           "Plat No",
           "Sopir",
           "Lokasi Jemput",
           "Lokasi Tujuan",
           "Waktu Jemput",
           "Status",
           "Keterangan"
       };

        
        model = new DefaultTableModel(null, Baris);
        tblDataPenyewaan.setModel(model);
        
        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int num = 1;
            while(hasil.next()){
                String[] data={
                    Integer.toString(num), 
                    hasil.getString("id"), 
                    hasil.getString("nomor_polisi"), 
                    hasil.getString("sopir"), 
                    hasil.getString("lokasi_jemput"), 
                    hasil.getString("lokasi_tujuan"), 
                    hasil.getString("waktu_jemput"), 
                    hasil.getString("status"),
                    hasil.getString("deskripsi")
                };
                model.addRow(data);
                num++;
            }
            TableActionEvent actionEvent = new TableActionEvent() {
                @Override
                public void onEdit(int row) {
                    DialogPenyewaanAddEdit dialog = setupDialogPenyewaan();
                    System.out.print(model.getValueAt(row, 1).toString());
                    dialog.setData(Integer.parseInt(model.getValueAt(row, 1).toString()));
                    dialog.setVisible(true);
                }

                @Override
                public void onDelete(int row) {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "Konfirmasi hapus penyewaan?","Warning",dialogButton);
                    if(dialogResult == JOptionPane.YES_OPTION){
                        String kode = model.getValueAt(row, 1).toString();
                        String sql = "DELETE FROM penyewaan_ambulan WHERE id = ?";
                        try{
                            PreparedStatement stat = conn.prepareStatement(sql);
                            stat.setString(1, kode);
                            stat.executeUpdate();
                            
                            JOptionPane.showMessageDialog(null, "Penyewaan Berhasil Dihapus");
                            loadDataPenyewaan();
                        }catch (SQLException e){
                            JOptionPane.showMessageDialog(null, "Penyewaan Gagal Dihapus "+e);
                        }
                    }
                }
            };
            tblDataPenyewaan.getColumnModel().getColumn(1).setCellRenderer(new TableActionCellRender());
            tblDataPenyewaan.getColumnModel().getColumn(1).setCellEditor(new TableActionCellEditor(actionEvent));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private DialogPenyewaanAddEdit setupDialogPenyewaan() {
        DialogPenyewaanAddEdit dialog = new DialogPenyewaanAddEdit(null, true);
        dialog.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
                
            }

            @Override
            public void windowClosing(WindowEvent e) {
                
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadDataPenyewaan();
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
                
            }
        });
        return dialog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAmbulan;
    private javax.swing.JButton btnAddPenyewaan;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReport1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private appcode.table.TableDark tblDataAmbulan;
    private appcode.table.TableDark tblDataPenyewaan;
    private appcode.form.CustomTextField txtSearch;
    private appcode.form.CustomTextField txtSearchPenyewaan;
    // End of variables declaration//GEN-END:variables
}
