/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Auth.Login;
import koneksi.Koneksi;
import Menu.MenuHome;
import Menu.MenuJenazah;
import Menu.MenuMakam;
import Menu.MenuPenyewaan;
import Menu.MenuReservasi;
import Menu.MenuTransaksi;
import Menu.MenuUser;
import appcode.Session;
import javax.swing.JFrame;
import javax.swing.*;
import sistem.informasi.pemakaman.*;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;

/**
 *
 * @author coyha
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private Connection conn = new Koneksi().connect();
    String fullName = "";
    private enum ListMenu {
        HOME,
        DATA_MAKAM,
        DATA_USER,
        DATA_JENAZAH,
        TRANSAKSI,
        RESERVASI,
        PENYEWAAN
    }
    private ListMenu activeMenu = ListMenu.HOME;
    
    public MainPage() {
        initComponents();
        this.fullName = Session.getNama();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        if (Session.getNama().equals("")){
            dispose();
        }
        if (Session.getRole().toLowerCase().equals("guest")){
            menuMakam.setVisible(false);
            menuUser.setVisible(false);
            menuJenazah.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuMakam = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menuUser = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        menuJenazah = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnLogout = new RoundedPanel(10, new java.awt.Color(255,153,153));
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        menuReservasi = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        menuTransaksi = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        menuPenyewaanAmbulan = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        labelPenyewaanAmbulan = new javax.swing.JLabel();
        panelWrapper = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelContent = new RoundedPanel(20, new java.awt.Color(255,255,255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 162, 161));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelMain.setBackground(new java.awt.Color(230, 244, 241));
        panelMain.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(64, 67, 69));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 697));

        jPanel1.setBackground(new java.awt.Color(64, 67, 69));
        jPanel1.setToolTipText("");
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(240, 570));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_new.png"))); // NOI18N

        menuHome.setBackground(new java.awt.Color(64, 67, 69));
        menuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuHomeMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_home.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");

        javax.swing.GroupLayout menuHomeLayout = new javax.swing.GroupLayout(menuHome);
        menuHome.setLayout(menuHomeLayout);
        menuHomeLayout.setHorizontalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHomeLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        menuHomeLayout.setVerticalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuMakam.setBackground(new java.awt.Color(64, 67, 69));
        menuMakam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuMakam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMakamMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMakamMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMakamMouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_grave.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Data Makam");

        javax.swing.GroupLayout menuMakamLayout = new javax.swing.GroupLayout(menuMakam);
        menuMakam.setLayout(menuMakamLayout);
        menuMakamLayout.setHorizontalGroup(
            menuMakamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuMakamLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuMakamLayout.setVerticalGroup(
            menuMakamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuUser.setBackground(new java.awt.Color(64, 67, 69));
        menuUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuUser.setPreferredSize(new java.awt.Dimension(169, 52));
        menuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuUserMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_user.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data User");

        javax.swing.GroupLayout menuUserLayout = new javax.swing.GroupLayout(menuUser);
        menuUser.setLayout(menuUserLayout);
        menuUserLayout.setHorizontalGroup(
            menuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUserLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuUserLayout.setVerticalGroup(
            menuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuJenazah.setBackground(new java.awt.Color(64, 67, 69));
        menuJenazah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuJenazah.setPreferredSize(new java.awt.Dimension(169, 52));
        menuJenazah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuJenazahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuJenazahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuJenazahMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_corpse.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Data Jenazah");

        javax.swing.GroupLayout menuJenazahLayout = new javax.swing.GroupLayout(menuJenazah);
        menuJenazah.setLayout(menuJenazahLayout);
        menuJenazahLayout.setHorizontalGroup(
            menuJenazahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJenazahLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuJenazahLayout.setVerticalGroup(
            menuJenazahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        btnLogout.setBackground(new java.awt.Color(255, 153, 153));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setOpaque(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setText("Logout");

        javax.swing.GroupLayout btnLogoutLayout = new javax.swing.GroupLayout(btnLogout);
        btnLogout.setLayout(btnLogoutLayout);
        btnLogoutLayout.setHorizontalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogoutLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnLogoutLayout.setVerticalGroup(
            btnLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        menuReservasi.setBackground(new java.awt.Color(64, 67, 69));
        menuReservasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuReservasi.setPreferredSize(new java.awt.Dimension(169, 52));
        menuReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReservasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuReservasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuReservasiMouseExited(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_reservasi.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Reservasi");

        javax.swing.GroupLayout menuReservasiLayout = new javax.swing.GroupLayout(menuReservasi);
        menuReservasi.setLayout(menuReservasiLayout);
        menuReservasiLayout.setHorizontalGroup(
            menuReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuReservasiLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuReservasiLayout.setVerticalGroup(
            menuReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        menuTransaksi.setBackground(new java.awt.Color(64, 67, 69));
        menuTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTransaksi.setPreferredSize(new java.awt.Dimension(169, 52));
        menuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_transaction.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Transaksi");

        javax.swing.GroupLayout menuTransaksiLayout = new javax.swing.GroupLayout(menuTransaksi);
        menuTransaksi.setLayout(menuTransaksiLayout);
        menuTransaksiLayout.setHorizontalGroup(
            menuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTransaksiLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuTransaksiLayout.setVerticalGroup(
            menuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuPenyewaanAmbulan.setBackground(new java.awt.Color(64, 67, 69));
        menuPenyewaanAmbulan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPenyewaanAmbulan.setPreferredSize(new java.awt.Dimension(169, 52));
        menuPenyewaanAmbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPenyewaanAmbulanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPenyewaanAmbulanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPenyewaanAmbulanMouseExited(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_ambulance.png"))); // NOI18N

        labelPenyewaanAmbulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPenyewaanAmbulan.setForeground(new java.awt.Color(255, 255, 255));
        labelPenyewaanAmbulan.setText("Penyewaan Ambulan");

        javax.swing.GroupLayout menuPenyewaanAmbulanLayout = new javax.swing.GroupLayout(menuPenyewaanAmbulan);
        menuPenyewaanAmbulan.setLayout(menuPenyewaanAmbulanLayout);
        menuPenyewaanAmbulanLayout.setHorizontalGroup(
            menuPenyewaanAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPenyewaanAmbulanLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPenyewaanAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        menuPenyewaanAmbulanLayout.setVerticalGroup(
            menuPenyewaanAmbulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPenyewaanAmbulan, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(menuUser, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(menuMakam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuJenazah, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(menuReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(menuTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(menuPenyewaanAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMakam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuJenazah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPenyewaanAmbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );

        panelMain.add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelWrapper.setBackground(new java.awt.Color(45, 48, 51));
        panelWrapper.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(45, 48, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(646, 115));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(45, 48, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(45, 48, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 746));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 864, Short.MAX_VALUE)
        );

        panelWrapper.add(jPanel6, java.awt.BorderLayout.LINE_START);

        panelContent.setBackground(new java.awt.Color(45, 48, 51));
        panelContent.setOpaque(false);
        panelContent.setLayout(new java.awt.BorderLayout());
        panelWrapper.add(panelContent, java.awt.BorderLayout.CENTER);

        panelMain.add(panelWrapper, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(962, 1018));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        setActiveMenu(ListMenu.HOME);
        panelContent.add(new MenuHome());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuHomeMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Konfirmasi logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnLogoutMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        panelContent.removeAll();
        setActiveMenu(ListMenu.HOME);
        panelContent.add(new MenuHome());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_formWindowOpened

    private void menuMakamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMakamMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        setActiveMenu(ListMenu.DATA_MAKAM);
        panelContent.add(new MenuMakam());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuMakamMouseClicked

    private void menuUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseClicked
        // TODO add your handling code here:
        panelContent.removeAll();
        setActiveMenu(ListMenu.DATA_USER);
        panelContent.add(new MenuUser());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuUserMouseClicked

    private void menuHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseEntered
        // TODO add your handling code here:
        menuHome.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuHomeMouseEntered

    private void menuHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.HOME){
            menuHome.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuHomeMouseExited

    private void menuMakamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMakamMouseEntered
        // TODO add your handling code here:
        menuMakam.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuMakamMouseEntered

    private void menuMakamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMakamMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.DATA_MAKAM){
            menuMakam.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuMakamMouseExited

    private void menuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseEntered
        // TODO add your handling code here:
        menuUser.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuUserMouseEntered

    private void menuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUserMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.DATA_USER){
            menuUser.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuUserMouseExited

    private void menuJenazahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJenazahMouseClicked
        // TODO add your handling code here:
        setActiveMenu(ListMenu.DATA_JENAZAH);
        panelContent.removeAll();
        panelContent.add(new MenuJenazah());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuJenazahMouseClicked

    private void menuJenazahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJenazahMouseEntered
        // TODO add your handling code here:
        menuJenazah.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuJenazahMouseEntered

    private void menuJenazahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuJenazahMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.DATA_JENAZAH){
            menuJenazah.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuJenazahMouseExited

    private void menuReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReservasiMouseClicked
        // TODO add your handling code here:
        setActiveMenu(ListMenu.RESERVASI);
        panelContent.removeAll();
        panelContent.add(new MenuReservasi());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuReservasiMouseClicked

    private void menuReservasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReservasiMouseEntered
        // TODO add your handling code here:
        menuReservasi.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuReservasiMouseEntered

    private void menuReservasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReservasiMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.RESERVASI){
            menuReservasi.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuReservasiMouseExited

    private void menuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseClicked
        // TODO add your handling code here:
        setActiveMenu(ListMenu.TRANSAKSI);
        panelContent.removeAll();
        panelContent.add(new MenuTransaksi());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuTransaksiMouseClicked

    private void menuTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseEntered
        // TODO add your handling code here:
        menuTransaksi.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuTransaksiMouseEntered

    private void menuTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.TRANSAKSI){
            menuTransaksi.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuTransaksiMouseExited

    private void menuPenyewaanAmbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenyewaanAmbulanMouseClicked
        // TODO add your handling code here:
        setActiveMenu(ListMenu.PENYEWAAN);
        panelContent.removeAll();
        panelContent.add(new MenuPenyewaan());
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_menuPenyewaanAmbulanMouseClicked

    private void menuPenyewaanAmbulanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenyewaanAmbulanMouseEntered
        // TODO add your handling code here:
        menuPenyewaanAmbulan.setBackground(new Color(195,176,136));
    }//GEN-LAST:event_menuPenyewaanAmbulanMouseEntered

    private void menuPenyewaanAmbulanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenyewaanAmbulanMouseExited
        // TODO add your handling code here:
        if (activeMenu != ListMenu.PENYEWAAN){
            menuPenyewaanAmbulan.setBackground(new Color(64,67,69));
        }
    }//GEN-LAST:event_menuPenyewaanAmbulanMouseExited

    private void setActiveMenu(ListMenu menu){
        menuHome.setBackground(new Color(64,67,69));
        menuUser.setBackground(new Color(64,67,69));
        menuMakam.setBackground(new Color(64,67,69));
        menuJenazah.setBackground(new Color(64,67,69));
        menuReservasi.setBackground(new Color(64,67,69));
        menuTransaksi.setBackground(new Color(64,67,69));
        menuPenyewaanAmbulan.setBackground(new Color(64,67,69));
        
        activeMenu = menu;
        
        switch (menu){
            case HOME:
                menuHome.setBackground(new Color(195,176,136));
                break;
            case DATA_USER:
                menuUser.setBackground(new Color(195,176,136));
                break;
            case DATA_MAKAM:
                menuMakam.setBackground(new Color(195,176,136));
                break;
            case DATA_JENAZAH:
                menuJenazah.setBackground(new Color(195,176,136));
                break;
            case RESERVASI:
                menuReservasi.setBackground(new Color(195,176,136));
                break;
            case TRANSAKSI:
                menuTransaksi.setBackground(new Color(195,176,136));
                break;
            default:
                menuPenyewaanAmbulan.setBackground(new Color(195,176,136));
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (Session.getNama().equals("")){
                    new Login().setVisible(true);
                    return;
                }
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelPenyewaanAmbulan;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuJenazah;
    private javax.swing.JPanel menuMakam;
    private javax.swing.JPanel menuPenyewaanAmbulan;
    private javax.swing.JPanel menuReservasi;
    private javax.swing.JPanel menuTransaksi;
    private javax.swing.JPanel menuUser;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelWrapper;
    // End of variables declaration//GEN-END:variables
}
